org: runbuddydev
service: service-a

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-1
  logRetentionInDays: 14

functions:
  lambdaA:
    handler: src/lambdaA.handler
    events:
      - httpApi:
          path: /testing
          method: post

package:
  individually: true

# Native ESBuild
build:
  esbuild:
    bundle: true
    minify: false
    exclude:
      - "aws-lambda"
      - "@aws-sdk/*"
# # ESBuild Plugin
# plugins:
#   - serverless-esbuild

# custom:
#   esbuild:
#     bundle: true
#     minify: false
#     exclude:
#       - "aws-lambda"y
#       - "@aws-sdk/*"

# build:
#   esbuild: false
